openapi: 3.0.0
info:
  title: Blog API
  description: OpenAPI collection for managing blog posts.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/blogs:
    get:
      summary: Retrieve All Blogs
      responses:
        '200':
          description: A list of blogs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Blog'
    post:
      summary: Create a Blog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlogCreate'
      responses:
        '201':
          description: Blog created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
  /api/blogs/{id}:
    get:
      summary: Retrieve a Blog
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the blog
          schema:
            type: string
      responses:
        '200':
          description: Details of a blog
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
        '404':
          description: Blog not found
    put:
      summary: Update a Blog
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the blog
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlogUpdate'
      responses:
        '200':
          description: Blog updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
        '404':
          description: Blog not found
    delete:
      summary: Delete a Blog
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the blog
          schema:
            type: string
      responses:
        '204':
          description: Blog deleted successfully
        '404':
          description: Blog not found
components:
  schemas:
    Blog:
      type: object
      properties:
        id:
          type: string
          example: "1"
        title:
          type: string
          example: "My First Blog"
        content:
          type: string
          example: "This is the content of my first blog."
        author:
          type: string
          example: "Adwaith Rajeev"
        tags:
          type: array
          items:
            type: string
          example: ["blog", "test"]
    BlogCreate:
      type: object
      required:
        - title
        - content
        - author
      properties:
        title:
          type: string
          example: "My First Blog"
        content:
          type: string
          example: "This is the content of my first blog."
        author:
          type: string
          example: "Adwaith Rajeev"
        tags:
          type: array
          items:
            type: string
          example: ["blog", "test"]
    BlogUpdate:
      type: object
      properties:
        title:
          type: string
          example: "Updated Blog Title"
        content:
          type: string
          example: "Updated blog content."
        author:
          type: string
          example: "Adwaith Rajeev"
